version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5176:5176"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - VITE_API_URL=https://apichatbotfit.andyanh.id.vn
      - VITE_APP_NAME=Chatbot HCMUTE - FIT
      - VITE_APP_DESCRIPTION=Chatbot trả lời các câu hỏi, thắc mắc liên quan đến Khoa CNTT SPKT TPHCM
      - VITE_APP_URL=https://chatbot.andyanh.id.vn
      - VITE_APP_VERSION=1.0.0
      - NODE_ENV=production
    extra_hosts:
      - "chatbot.andyanh.id.vn:127.0.0.1"
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge 